export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `Der Morgen bricht in Österreich an, und die Straßen von Wien erwachen zum Leben. Die Österreicher wachen auf mit dem Geruch von frischem Gebäck und dem Klang der Kirchenglocken.${ suffix }Maria, eine Einwohnerin von Salzburg, steht früh auf, um zum Markt zu gehen und frisches Obst und Gemüse für das Frühstück zu kaufen. Die Sonne strahlt über den majestätischen Alpen.${ suffix }In Graz machen sich die Pendler auf den Weg zur Arbeit, während in Innsbruck die Bergführer schon seit den frühen Morgenstunden unterwegs sind.${ suffix }Im Salzkammergut arbeiten die Bauern daran, das fruchtbare Land zu bestellen und die Tradition der Almwirtschaft zu bewahren.${ suffix }In Linz treffen sich die Menschen in den Kaffeehäusern, um ihren ersten Kaffee des Tages zu genießen und die Zeitung zu lesen.${ suffix }In der Steiermark laden die Weinberge zum Verkosten ein, während die Winzer ihre Trauben für den neuen Jahrgang ernten.${ suffix }In Klagenfurt bewundern die Besucher die prächtigen Gärten am Wörthersee und entspannen sich in der idyllischen Umgebung.${ suffix }In Tirol machen sich die Bergsteiger auf den Weg zu den Gipfeln der Alpen, um die atemberaubende Aussicht zu genießen.${ suffix }In Vorarlberg arbeiten die Handwerker in ihren Werkstätten und stellen traditionelle Holzarbeiten und Kunsthandwerk her.${ suffix }In Bregenz bereiten sich die Musiker auf die nächste Aufführung im berühmten Festspielhaus vor und proben fleißig.${ suffix }In St. Pölten erkunden die Touristen die historische Altstadt und besuchen die imposante barocke Kathedrale.${ suffix }In Eisenstadt üben die Musiker im Schloss Esterházy, um sich auf das nächste Konzert vorzubereiten und die Klänge von Haydn zu perfektionieren.${ suffix }In Kufstein genießen die Menschen einen Spaziergang entlang des malerischen Innufers und bewundern die Festung hoch über der Stadt.${ suffix }In Dornbirn treffen sich die Geschäftsleute zu Besprechungen und Verhandlungen in den modernen Bürogebäuden der Stadt.${ suffix }In Feldkirch flanieren die Menschen durch die engen Gassen der Altstadt und besuchen die gemütlichen Gasthäuser.${ suffix }In Baden bei Wien entspannen die Besucher in den Thermalbädern und genießen die heilenden Eigenschaften des mineralhaltigen Wassers.${ suffix }`,
    code: `de-AT`,
    macro: `de`,
  }
}
