export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `Der Morgen bricht in der Schweiz an, und die Straßen von Zürich erwachen zum Leben. Die Schweizer wachen auf mit dem Geruch von frischem Brot und dem Klang der Kuhglocken auf den Almen.${ suffix }Maria, eine Einwohnerin von Bern, steht früh auf, um zum Markt zu gehen und frisches Obst und Gemüse für das Frühstück zu kaufen. Die Sonne strahlt über den majestätischen Schweizer Alpen.${ suffix }In Genf machen sich die Pendler auf den Weg zur Arbeit, während in Luzern die Schifffahrtsgesellschaften schon seit den frühen Morgenstunden unterwegs sind.${ suffix }Im Appenzellerland arbeiten die Bauern daran, das fruchtbare Land zu bestellen und die Tradition der Käseherstellung zu bewahren.${ suffix }In Basel treffen sich die Menschen in den Cafés am Rhein, um ihren ersten Kaffee des Tages zu genießen und die Zeitung zu lesen.${ suffix }In Graubünden laden die Weinberge zum Verkosten ein, während die Winzer ihre Trauben für den neuen Jahrgang ernten.${ suffix }In Lausanne bewundern die Besucher die prächtigen Ufer des Genfer Sees und entspannen sich in der idyllischen Umgebung.${ suffix }In St. Gallen machen sich die Wanderer auf den Weg zu den Gipfeln der Alpen, um die atemberaubende Aussicht zu genießen.${ suffix }Im Tessin arbeiten die Handwerker in ihren Werkstätten und stellen traditionelle Tessiner Spezialitäten wie Polenta und Risotto her.${ suffix }In Zug bereiten sich die Musiker auf die nächste Aufführung im berühmten Theater Casino vor und proben fleißig.${ suffix }In Thurgau erkunden die Touristen die historische Altstadt von Kreuzlingen und besuchen die imposante Konzilstadt Konstanz auf der anderen Seite des Bodensees.${ suffix }In Neuenburg üben die Musiker im Schloss von Neuenburg, um sich auf das nächste Konzert vorzubereiten und die Klänge von Beethoven zu perfektionieren.${ suffix }In Aargau genießen die Menschen einen Spaziergang entlang des malerischen Rheinufers und bewundern die mittelalterlichen Burgen und Schlösser.${ suffix }In Schaffhausen treffen sich die Geschäftsleute zu Besprechungen und Verhandlungen in den modernen Bürogebäuden der Stadt.${ suffix }In Winterthur flanieren die Menschen durch die engen Gassen der Altstadt und besuchen die gemütlichen Brauereigasthäuser.${ suffix }In Obwalden entspannen die Besucher in den Thermalbädern und genießen die heilenden Eigenschaften des mineralhaltigen Wassers.${ suffix }`,
    code: `de-CH`,
    macro: `de`,
  }
}
