export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `Der Morgen bricht in Liechtenstein an, und die Straßen von Vaduz erwachen langsam zum Leben. Die Liechtensteiner wachen auf mit dem Geruch von frischem Brot und dem Klang der Kirchenglocken in den kleinen Dörfern.${ suffix }Maria, eine Einwohnerin von Schaan, steht früh auf, um zum Markt zu gehen und frisches Obst und Gemüse für das Frühstück zu kaufen. Die Sonne strahlt über den majestätischen Alpen.${ suffix }In Balzers machen sich die Pendler auf den Weg zur Arbeit, während in Triesen die Wanderer schon seit den frühen Morgenstunden unterwegs sind.${ suffix }In den Weinbergen von Bendern arbeiten die Winzer daran, die Reben zu pflegen und den hervorragenden Wein zu produzieren, für den Liechtenstein bekannt ist.${ suffix }In Eschen treffen sich die Menschen in den kleinen Cafés, um ihren ersten Kaffee des Tages zu genießen und die Zeitung zu lesen.${ suffix }In Mauren laden die Weinberge zum Verkosten ein, während die Winzer ihre Trauben für den neuen Jahrgang ernten.${ suffix }In Triesenberg bewundern die Besucher das malerische Bergpanorama und entspannen sich in der idyllischen Umgebung.${ suffix }In Schellenberg machen sich die Touristen auf den Weg zu einer gemütlichen Wanderung durch die Alpen und genießen die frische Bergluft.${ suffix }In Gamprin arbeiten die Handwerker in ihren Werkstätten und stellen traditionelle liechtensteinische Produkte wie Käse und Wurst her.${ suffix }In Ruggell bereiten sich die Musiker auf die nächste Aufführung im örtlichen Kulturzentrum vor und proben fleißig.${ suffix }In Planken erkunden die Touristen die historische Altstadt und besuchen das moderne Kunstmuseum Liechtenstein.${ suffix }In Vaduz üben die Musiker im Konzertsaal des Kulturzentrums, um sich auf das nächste Konzert vorzubereiten und die Klänge von Beethoven zu perfektionieren.${ suffix }In Schaanberg genießen die Menschen einen Spaziergang entlang der malerischen Flüsse und Bäche und bewundern die mittelalterlichen Burgen.${ suffix }In Vaduz treffen sich die Geschäftsleute zu Besprechungen und Verhandlungen in den modernen Bürogebäuden der Stadt.${ suffix }In Nendeln flanieren die Menschen durch die engen Gassen der Altstadt und besuchen die gemütlichen Restaurants und Bistros.${ suffix }In Balzers entspannen die Besucher in den Thermalbädern und genießen die heilenden Eigenschaften des mineralhaltigen Wassers.${ suffix }`,
    code: `de-LI`,
    macro: `de`,
  }
}
