export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `Der Morgen bricht in Luxemburg an, und die Straßen von Luxemburg-Stadt erwachen zum Leben. Die Luxemburger wachen auf mit dem Geruch von frisch gebackenem Brot und dem Klang der Kirchenglocken in den kleinen Dörfern.${ suffix }Maria, eine Einwohnerin von Esch-sur-Alzette, steht früh auf, um zum Markt zu gehen und frisches Obst und Gemüse für das Frühstück zu kaufen. Die Sonne strahlt über den malerischen Ardennen.${ suffix }In Diekirch machen sich die Pendler auf den Weg zur Arbeit, während in Echternach die Wanderer schon seit den frühen Morgenstunden unterwegs sind.${ suffix }In der Moselregion arbeiten die Winzer daran, die Reben zu pflegen und den hervorragenden Wein zu produzieren, für den Luxemburg bekannt ist.${ suffix }In Belval treffen sich die Menschen in den Cafés, um ihren ersten Kaffee des Tages zu genießen und die Zeitung zu lesen.${ suffix }In Grevenmacher laden die Weinberge zum Verkosten ein, während die Winzer ihre Trauben für den neuen Jahrgang ernten.${ suffix }In Vianden bewundern die Besucher das majestätische Schloss Vianden und entspannen sich in der idyllischen Umgebung.${ suffix }In Remich machen sich die Touristen auf den Weg zu einer gemütlichen Schifffahrt auf der Mosel und genießen die malerische Landschaft.${ suffix }In Esch-sur-Sûre arbeiten die Handwerker in ihren Werkstätten und stellen traditionelle luxemburgische Produkte wie Käse und Schinken her.${ suffix }In Wiltz bereiten sich die Musiker auf die nächste Aufführung im Kulturzentrum in den Ardennen vor und proben fleißig.${ suffix }In Dudelange erkunden die Touristen die historische Altstadt und besuchen das moderne Nationalmuseum der Geschichte und Kunst.${ suffix }In Mersch üben die Musiker in der örtlichen Musikhalle, um sich auf das nächste Konzert vorzubereiten und die Klänge von Mozart zu perfektionieren.${ suffix }In Clervaux genießen die Menschen einen Spaziergang entlang der idyllischen Wälder und Bäche und bewundern die mittelalterliche Burg.${ suffix }In Luxembourg-Gare treffen sich die Geschäftsleute zu Besprechungen und Verhandlungen in den modernen Bürogebäuden der Stadt.${ suffix }In Ettelbrück flanieren die Menschen durch die engen Gassen der Altstadt und besuchen die gemütlichen Restaurants und Brauereien.${ suffix }In Mondorf-les-Bains entspannen die Besucher in den Thermalbädern und genießen die heilenden Eigenschaften des mineralhaltigen Wassers.${ suffix }`,
    code: `de-LU`,
    macro: `de`,
  }
}
