export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a Cuba, iluminando las calles coloridas de La Habana y las playas de arena blanca de Varadero. Los habaneros se despiertan con el aroma del café y el sonido de la música salsa en las calles.${ suffix }María, una residente de Santiago de Cuba, se levanta temprano para preparar el desayuno mientras escucha el canto de los gallos en el patio. El sol brilla sobre la Sierra Maestra.${ suffix }En Viñales, los campesinos trabajan en los campos de tabaco, cultivando las hojas que serán utilizadas para hacer los famosos cigarros cubanos.${ suffix }En Trinidad, los turistas recorren las calles empedradas del casco antiguo, admirando la arquitectura colonial y la artesanía local.${ suffix }En Cienfuegos, los pescadores salen al mar en sus pequeñas embarcaciones, buscando la captura del día para vender en el mercado local.${ suffix }En Santa Clara, los estudiantes universitarios se preparan para un nuevo día de clases en la Universidad Central de Las Villas.${ suffix }En Holguín, los músicos se reúnen en los parques para tocar música tradicional cubana, llenando el aire con ritmos caribeños.${ suffix }En Cayo Coco, los turistas disfrutan del sol y el mar en las playas paradisíacas, relajándose en los complejos turísticos todo incluido.${ suffix }En Matanzas, los bailarines de rumba practican en los patios traseros, preservando esta forma de expresión cultural única.${ suffix }En Pinar del Río, los turistas visitan las plantaciones de tabaco y las fábricas de cigarros, aprendiendo sobre el proceso de producción.${ suffix }En Camagüey, los artistas plásticos exhiben sus obras en los estudios y galerías de la ciudad, mostrando la riqueza cultural de la región.${ suffix }En Isla de la Juventud, los buceadores exploran los arrecifes de coral, maravillándose con la diversidad de vida marina.${ suffix }En Guantánamo, los agricultores cultivan café y cacao en las tierras montañosas, contribuyendo a la economía agrícola del país.${ suffix }En Artemisa, los campesinos recolectan mangos y piñas en los campos, aprovechando los frutos de la tierra cubana.${ suffix }En Las Tunas, los músicos de trova improvisan canciones en los bares y peñas, compartiendo historias y emociones a través de la música.${ suffix }`,
    code: `es-CU`,
    macro: `es`,
  }
}
