export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a Costa Rica, iluminando las selvas tropicales de Monteverde y las playas de arena dorada de Manuel Antonio. Los costarricenses se despiertan con el aroma del café recién preparado y el sonido de los pájaros cantando en la naturaleza.${ suffix }María, una residente de San José, se levanta temprano para ir a su trabajo en el centro de la ciudad mientras el sol empieza a asomarse entre los edificios. El clima fresco de la capital la acompaña en su trayecto.${ suffix }En la Península de Nicoya, los surfistas aprovechan las olas perfectas mientras los vendedores ambulantes ofrecen cocos fríos y ceviche fresco.${ suffix }En el Caribe, los pescadores salen al mar en sus pequeñas embarcaciones, buscando la captura del día para vender en los mercados locales.${ suffix }En la región de Arenal, los turistas se maravillan con el volcán activo y las aguas termales, relajándose en medio de la naturaleza.${ suffix }En Limón, los lugareños celebran el carnaval con música, baile y desfiles coloridos que reflejan la riqueza cultural de la región.${ suffix }En Tortuguero, los turistas exploran los canales de agua en busca de vida silvestre, observando tortugas marinas, caimanes y una variedad de aves.${ suffix }En la provincia de Guanacaste, los rancheros montan a caballo a través de las extensas llanuras, admirando los paisajes secos y la diversidad de la vida salvaje.${ suffix }En la región de Sarapiquí, los ecoturistas se aventuran en caminatas por la selva, descubriendo una amplia gama de flora y fauna.${ suffix }En la Cordillera de Talamanca, los excursionistas hacen senderismo hasta llegar a las cimas de las montañas, disfrutando de vistas impresionantes y aire fresco.${ suffix }En Cartago, los peregrinos visitan la Basílica de Nuestra Señora de los Ángeles, patróna de Costa Rica, para hacer oraciones y dejar ofrendas.${ suffix }En la región del Pacífico Sur, los amantes del buceo exploran los arrecifes de coral y los restos de naufragios, maravillándose con la rica vida marina.${ suffix }En la región de los Santos, los artesanos tallan figuras de madera y crean hermosas máscaras para celebrar las fiestas tradicionales.${ suffix }En las montañas de Talamanca, los indígenas bribri y cabécar preservan su cultura ancestral, compartiendo su conocimiento sobre la naturaleza y la medicina tradicional.${ suffix }`,
    code: `es-CR`,
    macro: `es`,
  }
}
