export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a la República Dominicana, iluminando las calles de Santo Domingo y las playas de arena blanca de Punta Cana. Los dominicanos se despiertan con el aroma del café y el sonido de la música merengue en las radios.${ suffix }María, una residente de Santiago de los Caballeros, se levanta temprano para ir al mercado a comprar frutas frescas y vegetales para el desayuno. El sol brilla sobre las montañas de la Cordillera Central.${ suffix }En la Zona Colonial, los turistas recorren las calles empedradas y visitan las antiguas fortalezas españolas, maravillándose con la historia colonial del país.${ suffix }En la región este, los pescadores salen al mar en sus embarcaciones coloridas, buscando la captura del día para vender en los mercados locales.${ suffix }En la región norte, los agricultores cosechan plátanos y cacao en los valles fértiles, contribuyendo a la economía agrícola del país.${ suffix }En las playas de la Costa Norte, los turistas disfrutan del sol y el mar mientras los vendedores ambulantes ofrecen cocos fríos y empanadas de pescado.${ suffix }En La Romana, los golfistas juegan en los campos de golf de clase mundial, rodeados de exuberante vegetación y vistas al mar.${ suffix }En el Cibao, los músicos tocan bachata en los bares y clubes nocturnos, compartiendo la música típica dominicana con lugareños y visitantes.${ suffix }En Samaná, los turistas se maravillan con el espectáculo de las ballenas jorobadas que visitan las aguas cálidas de la bahía durante el invierno.${ suffix }En Barahona, los ecoturistas exploran los parques nacionales y las reservas naturales, maravillándose con la diversidad de paisajes y vida silvestre.${ suffix }En Puerto Plata, los turistas visitan el teleférico que sube a la cima del monte Isabel de Torres, disfrutando de vistas panorámicas de la ciudad y el mar.${ suffix }En Jarabacoa, los aventureros se lanzan en tirolina sobre los ríos y cascadas, disfrutando de la emoción de la naturaleza.${ suffix }En Higüey, los peregrinos visitan la Basílica de Nuestra Señora de la Altagracia, patrona del país, para hacer oraciones y dejar ofrendas.${ suffix }En Pedernales, los excursionistas exploran las cuevas y acantilados de la costa sur, descubriendo paisajes impresionantes y playas desiertas.${ suffix }En Monte Cristi, los kite surfistas aprovechan los vientos alisios para deslizarse sobre las olas del océano Atlántico.${ suffix }`,
    code: `es-DO`,
    macro: `es`,
  }
}
