export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a Guatemala, iluminando las calles de la Ciudad de Guatemala y las ruinas mayas de Tikal. Los guatemaltecos se despiertan con el aroma del café y el sonido de las aves en la selva.${ suffix }María, una residente de Antigua Guatemala, se levanta temprano para ir al mercado a comprar frutas frescas y tortillas para el desayuno. El sol brilla sobre los volcanes.${ suffix }En la capital, los estudiantes se preparan para un nuevo día de clases en la Universidad de San Carlos de Guatemala, mientras los trabajadores comienzan su jornada en el centro histórico.${ suffix }En el altiplano occidental, los agricultores cultivan maíz y frijoles en las terrazas agrícolas, siguiendo las tradiciones ancestrales de sus antepasados.${ suffix }En Quetzaltenango, los turistas visitan las aguas termales de Fuentes Georginas y disfrutan de un día de relajación en medio de la naturaleza.${ suffix }En el Lago de Atitlán, los turistas exploran los pueblos indígenas a orillas del lago y disfrutan de las vistas panorámicas de los volcanes.${ suffix }En la región de Petén, los arqueólogos trabajan en las excavaciones de las ruinas mayas, descubriendo los secretos de esta antigua civilización.${ suffix }En Izabal, los turistas visitan el Parque Nacional Río Dulce y navegan por el cañón del río, admirando la exuberante vegetación y la vida silvestre.${ suffix }En Alta Verapaz, los turistas exploran las cuevas de Lanquín y Semuc Champey, nadando en las pozas de agua turquesa y admirando las formaciones rocosas.${ suffix }En Chichicastenango, los turistas visitan el mercado al aire libre más grande de Centroamérica, donde pueden comprar artesanías y productos locales.${ suffix }En Huehuetenango, los turistas disfrutan del paisaje montañoso y visitan las cascadas de Chilascó y Los Cenotes, dos de las atracciones naturales más impresionantes.${ suffix }En Sololá, los turistas visitan las cooperativas de tejedoras y aprenden sobre la elaboración de textiles tradicionales, una de las principales artesanías del país.${ suffix }En El Quiché, los turistas visitan el sitio arqueológico de Iximché y aprenden sobre la historia de los mayas y la conquista española.${ suffix }En Sacatepéquez, los turistas disfrutan del festival de barriletes gigantes en el Día de los Muertos, una tradición colorida y emocionante.${ suffix }En Baja Verapaz, los turistas visitan el Parque Nacional Cuevas de Candelaria y exploran las cuevas y formaciones rocosas.${ suffix }`,
    code: `es-GT`,
    macro: `es`,
  }
}
