export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a Honduras, iluminando las calles de Tegucigalpa y las playas de arena blanca de Roatán. Los hondureños se despiertan con el aroma del café y el sonido de los pájaros en la selva.${ suffix }María, una residente de San Pedro Sula, se levanta temprano para ir al mercado a comprar frutas frescas y tortillas para el desayuno. El sol brilla sobre el valle de Sula.${ suffix }En la capital, los estudiantes se preparan para un nuevo día de clases en la Universidad Nacional Autónoma de Honduras, mientras los trabajadores comienzan su jornada en el centro de la ciudad.${ suffix }En la región de Copán, los arqueólogos trabajan en las ruinas mayas, preservando la historia y cultura de la región.${ suffix }En La Ceiba, los turistas disfrutan del carnaval más grande de Honduras, con desfiles, música y bailes tradicionales.${ suffix }En las Islas de la Bahía, los buceadores exploran los arrecifes de coral y los restos de naufragios, maravillándose con la rica vida marina.${ suffix }En Comayagua, los turistas visitan la Catedral de Santa María, una de las más antiguas de América Central, y disfrutan de la arquitectura colonial.${ suffix }En Gracias, los turistas exploran las montañas y cascadas de la región, disfrutando de la belleza natural.${ suffix }En la región de Olancho, los agricultores cultivan café y cacao en las laderas de las montañas, contribuyendo a la economía agrícola del país.${ suffix }En El Paraíso, los turistas visitan el Parque Nacional La Tigra, una reserva natural que alberga una gran diversidad de flora y fauna.${ suffix }En Islas de la Bahía, los pescadores salen al mar en busca de langostas y pargos, mientras los turistas disfrutan de la pesca deportiva.${ suffix }En Valle, los agricultores recolectan frutas tropicales como piñas y mangos en los campos fértiles del valle de Jamastrán.${ suffix }En Lempira, los excursionistas hacen senderismo hasta llegar a la cima del Cerro las Minas, el pico más alto de Honduras.${ suffix }En Intibucá, los artesanos trabajan en telares tradicionales, creando hermosas piezas de tejido a mano.${ suffix }En la Mosquitia, los turistas exploran la selva tropical y los ríos de la región, descubriendo una gran diversidad de vida silvestre.${ suffix }`,
    code: `es-HN`,
    macro: `es`,
  }
}
