export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana despunta en México, iluminando los coloridos mercados y las calles empedradas de los pueblos mágicos. Los vendedores callejeros comienzan a instalar sus puestos, ofreciendo frutas frescas y antojitos.${ suffix }María, una residente de Ciudad de México, se levanta temprano para preparar el desayuno mientras escucha el canto de los pájaros en el patio. El aroma del café recién hecho llena la cocina.${ suffix }En Oaxaca, los artesanos trabajan en sus talleres, creando hermosas piezas de barro y textiles tradicionales. Los colores brillantes y los diseños intrincados llenan el aire.${ suffix }En la Riviera Maya, los turistas disfrutan del sol y la arena en las hermosas playas de arena blanca, mientras los vendedores ambulantes ofrecen cocos frescos y artesanías locales.${ suffix }En Guadalajara, los mariachis recorren las calles, llenando el aire con música y alegría. Los restaurantes y bares se preparan para una noche de fiesta y diversión.${ suffix }En Chiapas, los indígenas tzotziles y tzeltales venden sus productos en los mercados locales, compartiendo su rica cultura y tradiciones con los visitantes.${ suffix }En Monterrey, los ejecutivos se apresuran hacia las oficinas mientras los regiomontanos disfrutan de un desayuno de tacos en los puestos callejeros.${ suffix }En Puebla, los pobladores se reúnen en el zócalo para celebrar las fiestas patrias, con música, baile y fuegos artificiales.${ suffix }En Mérida, los turistas exploran las ruinas mayas de Chichén Itzá, maravillándose con la grandeza de esta antigua civilización.${ suffix }En Veracruz, los pescadores salen al mar al amanecer, regresando más tarde con una abundante pesca para vender en el mercado.${ suffix }En Tijuana, los chefs fusionan la cocina mexicana con influencias internacionales, creando platillos únicos que reflejan la diversidad de la región.${ suffix }En el Bajío, los campos de agave se extienden hasta donde alcanza la vista, listos para ser cosechados y convertidos en tequila.${ suffix }En los barrios de Ciudad de México, los jóvenes se reúnen en cafeterías y galerías de arte, compartiendo ideas y expresando su creatividad.${ suffix }En Cancún, los turistas se aventuran en emocionantes excursiones de buceo y snorkel, explorando los arrecifes de coral y la vida marina.${ suffix }En Chiapas, la selva tropical ofrece refugio a una increíble diversidad de flora y fauna, con cascadas ocultas y ruinas antiguas esperando ser descubiertas.${ suffix }`,
    code: `es-MX`,
    macro: `es`,
  }
}
