export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a Nicaragua, iluminando las calles de Managua y las costas del Pacífico en San Juan del Sur. Los nicaragüenses se despiertan con el aroma del gallo pinto y el sonido de las olas en la playa.${ suffix }María, una residente de Granada, se levanta temprano para ir al mercado a comprar frutas frescas y queso para el desayuno. El sol brilla sobre el lago Cocibolca.${ suffix }En la capital, los estudiantes se preparan para un nuevo día de clases en la Universidad Nacional Autónoma de Nicaragua, mientras los trabajadores comienzan su jornada en el centro de la ciudad.${ suffix }En la región de Jinotega, los agricultores cosechan café en las montañas, contribuyendo a la economía agrícola del país.${ suffix }En Matagalpa, los turistas visitan las fincas cafetaleras y aprenden sobre el proceso de producción del café, desde la cosecha hasta la taza.${ suffix }En la Isla de Ometepe, los turistas exploran los volcanes Concepción y Maderas, disfrutando de la naturaleza virgen y las vistas panorámicas.${ suffix }En León, los turistas visitan la Catedral de León, la más grande de América Central, y disfrutan de la arquitectura colonial.${ suffix }En la región del Caribe, los pescadores salen al mar en sus pangas, buscando langostas y camarones para vender en los mercados locales.${ suffix }En la Costa Atlántica, los turistas disfrutan del sol y el mar en las playas de Corn Island y Little Corn Island, dos paraísos tropicales.${ suffix }En Masaya, los artesanos trabajan en el Mercado de Artesanías, creando hermosas piezas de cerámica, madera y textiles.${ suffix }En Rivas, los turistas visitan la Reserva Natural Chocoyero-El Brujo, donde pueden observar una gran variedad de aves y disfrutar de las cascadas.${ suffix }En Chinandega, los turistas visitan el Volcán San Cristóbal, el más alto de Nicaragua, y disfrutan de las vistas panorámicas desde la cima.${ suffix }En la región de Río San Juan, los turistas exploran los canales de agua dulce y observan la vida silvestre en el Refugio de Vida Silvestre Los Guatuzos.${ suffix }En Estelí, los turistas visitan las cooperativas de tabaco y aprenden sobre el proceso de fabricación de los puros, una de las principales industrias de la región.${ suffix }En Nueva Segovia, los turistas disfrutan del paisaje montañoso y las fincas de café, explorando la belleza natural de la región.${ suffix }`,
    code: `es-NI`,
    macro: `es`,
  }
}
