export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a Paraguay, iluminando las calles de Asunción y las extensas llanuras del Chaco. Los paraguayos se despiertan con el aroma del tereré y el sonido de los pájaros en el campo.${ suffix }María, una residente de Encarnación, se levanta temprano para ir al mercado a comprar frutas frescas y chipas para el desayuno. El sol brilla sobre el río Paraná.${ suffix }En la capital, los estudiantes se preparan para un nuevo día de clases en la Universidad Nacional de Asunción, mientras los trabajadores comienzan su jornada en el microcentro.${ suffix }En la región del Chaco, los ganaderos cuidan del ganado en las estancias y preservan la cultura criolla del país.${ suffix }En Ciudad del Este, los comerciantes se preparan para un día en el Mercado de Abasto, uno de los más grandes de la región, donde se puede encontrar de todo.${ suffix }En Itapúa, los turistas visitan las misiones jesuíticas guaraníes, un Patrimonio de la Humanidad, y disfrutan de la tranquilidad del campo.${ suffix }En Caaguazú, los agricultores cultivan soja y maíz en los campos fértiles del departamento, contribuyendo a la economía agrícola del país.${ suffix }En Concepción, los pescadores salen al río Paraguay en busca de surubíes y pacúes, mientras los turistas disfrutan de la pesca deportiva.${ suffix }En Guairá, los turistas visitan el Salto del Monday y se maravillan con la impresionante cascada rodeada de exuberante vegetación.${ suffix }En Paraguarí, los artesanos venden sus productos en la feria de la Plaza de los Héroes, mostrando su arte y habilidad.${ suffix }En Ñeembucú, los navegantes exploran el río Paraná en botes y lanchas, observando la fauna y flora de la región.${ suffix }En Alto Paraná, los trabajadores se desempeñan en las industrias y fábricas de la zona, contribuyendo al desarrollo económico del departamento.${ suffix }En Canindeyú, los agricultores cultivan tabaco en los campos del departamento, una de las principales actividades económicas de la región.${ suffix }En Amambay, los turistas visitan la Reserva Natural Cerro Corá, donde se libró la última batalla de la Guerra de la Triple Alianza.${ suffix }En Caazapá, los peregrinos visitan la Basílica de Caacupé, patrona de Paraguay, para hacer oraciones y dejar ofrendas.${ suffix }`,
    code: `es-PY`,
    macro: `es`,
  }
}
