export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a Puerto Rico, iluminando las coloridas calles de San Juan y las playas de arena blanca de Vieques. Los puertorriqueños se despiertan con el aroma del café y el sonido de las olas rompiendo en la costa.${ suffix }María, una residente de Ponce, se levanta temprano para preparar el desayuno mientras el sol se asoma por las montañas. El clima tropical y la brisa del mar le dan energía para empezar el día.${ suffix }En el Viejo San Juan, los turistas pasean por las estrechas calles adoquinadas, admirando la arquitectura colonial española y disfrutando de la música callejera.${ suffix }En la región montañosa de El Yunque, los excursionistas exploran la exuberante selva tropical y se bañan en las refrescantes cascadas.${ suffix }En la región oeste, los agricultores cosechan plátanos y café en los fértiles valles, contribuyendo a la agricultura de la isla.${ suffix }En las playas de Rincón, los surfistas disfrutan de las olas mientras los vendedores ambulantes ofrecen cocos fríos y pinchos de carne.${ suffix }En la Bahía Bioluminiscente de Fajardo, los visitantes se maravillan con el fenómeno natural de las aguas brillantes mientras reman en kayaks por la laguna.${ suffix }En Mayagüez, los estudiantes universitarios se preparan para un nuevo día de clases en la Universidad de Puerto Rico.${ suffix }En la región central, los artesanos trabajan en talleres familiares, creando hermosas artesanías de barro y madera.${ suffix }En Arecibo, los astrónomos estudian el cielo desde el famoso radiotelescopio, buscando señales de vida en el universo.${ suffix }En Guayama, los pescadores salen al mar en sus botes de pesca, regresando con una abundante captura de langosta y pescado fresco.${ suffix }En la Isla Culebra, los buceadores exploran los arrecifes de coral y los restos de naufragios, disfrutando de la rica vida marina.${ suffix }En la región sur, los músicos de bomba y plena tocan en las calles, compartiendo la rica tradición musical de la isla con los lugareños y visitantes.${ suffix }En la Cordillera Central, los excursionistas suben a las montañas para disfrutar de vistas panorámicas y cascadas escondidas.${ suffix }En la Isla Mona, los biólogos estudian la diversidad de especies en este paraíso natural protegido.${ suffix }`,
    code: `es-PR`,
    macro: `es`,
  }
}
