export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a Panamá, iluminando las calles de la Ciudad de Panamá y las selvas del Darién. Los panameños se despiertan con el aroma del café y el sonido de los pájaros en la naturaleza.${ suffix }María, una residente de Colón, se levanta temprano para ir al mercado a comprar frutas frescas y pescado para el desayuno. El sol brilla sobre el Mar Caribe.${ suffix }En la capital, los estudiantes se preparan para un nuevo día de clases en la Universidad de Panamá, mientras los trabajadores comienzan su jornada en el distrito financiero.${ suffix }En la región de Chiriquí, los agricultores cosechan café en las tierras altas, contribuyendo a la economía agrícola del país.${ suffix }En Bocas del Toro, los turistas disfrutan del snorkel y el buceo en las aguas cristalinas, explorando los arrecifes de coral y la vida marina.${ suffix }En la provincia de Los Santos, los artesanos trabajan en talleres familiares, creando hermosas máscaras y artesanías para las festividades locales.${ suffix }En el Archipiélago de San Blas, los indígenas Guna Yala preservan su cultura y tradiciones ancestrales, compartiendo su conocimiento con los visitantes.${ suffix }En Veraguas, los turistas visitan el Parque Nacional Coiba, una reserva natural que alberga una gran diversidad de flora y fauna.${ suffix }En Herrera, los turistas visitan las ruinas de la antigua ciudad de Natá, una de las primeras ciudades fundadas en el continente americano.${ suffix }En Coclé, los turistas disfrutan del sol y el mar en las playas de Farallón y Santa Clara, relajándose en el paraíso tropical.${ suffix }En la región de Darién, los ecoturistas exploran la selva tropical y observan la vida silvestre en el Parque Nacional Darién, una de las áreas protegidas más grandes de América Central.${ suffix }En Panamá Oeste, los turistas visitan el Parque Nacional Soberanía y disfrutan de la observación de aves y las caminatas por la selva.${ suffix }En Panamá Este, los turistas disfrutan del ecoturismo en el Parque Nacional Portobelo, explorando las fortalezas coloniales y las playas vírgenes.${ suffix }En la comarca Ngäbe-Buglé, los indígenas preservan su cultura y tradiciones, compartiendo su conocimiento sobre la medicina tradicional y la artesanía.${ suffix }En la región de Emberá-Wounaan, los turistas exploran los ríos y selvas, aprendiendo sobre las tradiciones y costumbres de las comunidades indígenas.${ suffix }`,
    code: `es-PA`,
    macro: `es`,
  }
}
