export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega al Perú, iluminando los picos nevados de los Andes y las antiguas ruinas de Machu Picchu. Los limeños se despiertan con el aroma del café y el sonido del tráfico en las calles de la capital.${ suffix }María, una residente de Arequipa, se levanta temprano para preparar el desayuno mientras contempla el majestuoso volcán Misti desde su ventana.${ suffix }En la selva amazónica, los indígenas parten en canoas por los ríos, buscando la pesca del día y recolectando frutas silvestres.${ suffix }En Cusco, los turistas se preparan para explorar las maravillas arqueológicas de la región, maravillándose con la historia de los incas.${ suffix }En la región costera, los pescadores salen al mar en sus pequeñas embarcaciones, buscando la pesca del día para abastecer los mercados locales.${ suffix }En el Valle Sagrado, los agricultores cultivan maíz y otros productos agrícolas utilizando técnicas ancestrales transmitidas de generación en generación.${ suffix }En Trujillo, los historiadores estudian las antiguas culturas preincaicas, explorando las pirámides de adobe y los complejos arqueológicos.${ suffix }En Puno, los lugareños celebran el Inti Raymi con danzas folclóricas y rituales tradicionales, honrando al sol y a la madre tierra.${ suffix }En Iquitos, los turistas se aventuran en emocionantes expediciones por la selva, observando la diversidad de flora y fauna amazónica.${ suffix }En Tacna, los agricultores trabajan en los campos de olivos y viñedos, produciendo aceitunas y vinos de alta calidad.${ suffix }En la región de Ayacucho, los artesanos crean hermosas artesanías de cerámica y tejidos, mostrando su habilidad y creatividad.${ suffix }En Chiclayo, los arqueólogos descubren nuevos hallazgos en las tumbas de Sipán, enriqueciendo nuestra comprensión de la historia precolombina.${ suffix }En Huancayo, los campesinos celebran la fiesta de la Virgen de la Inmaculada Concepción con coloridas procesiones y danzas típicas.${ suffix }En Piura, los surfistas disfrutan de las olas en las playas vírgenes, mientras los pescadores regresan con su pesca del día.${ suffix }En la región de Junín, los pastores cuidan de sus rebaños de alpacas y llamas, animales sagrados para la cultura andina.${ suffix }`,
    code: `es-PE`,
    macro: `es`,
  }
}
