export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a El Salvador, iluminando las calles de San Salvador y las playas de arena negra de La Libertad. Los salvadoreños se despiertan con el aroma del café y el sonido de las aves en los árboles.${ suffix }María, una residente de Santa Ana, se levanta temprano para ir al mercado a comprar frutas frescas y pupusas para el desayuno. El sol brilla sobre las montañas de la cordillera.${ suffix }En la capital, los estudiantes se preparan para un nuevo día de clases en la Universidad de El Salvador, mientras los trabajadores comienzan su jornada en el centro de la ciudad.${ suffix }En la región de Sonsonate, los agricultores cultivan café y caña de azúcar en los fértiles valles, contribuyendo a la economía agrícola del país.${ suffix }En la Ruta de las Flores, los turistas disfrutan del paisaje pintoresco y de las coloridas ferias artesanales que se celebran en los pueblos a lo largo del camino.${ suffix }En Suchitoto, los turistas visitan las antiguas iglesias coloniales y disfrutan de la arquitectura colonial y de las vistas del lago Suchitlán.${ suffix }En la región oriental, los pescadores salen al mar en sus embarcaciones tradicionales, buscando la captura del día para vender en los mercados locales.${ suffix }En Ahuachapán, los turistas visitan los baños termales de Santa Teresa y disfrutan de un día de relajación y bienestar.${ suffix }En San Miguel, los surfistas disfrutan de las olas en las playas de El Cuco y El Tamarindo, dos de los destinos más populares para practicar este deporte.${ suffix }En el departamento de La Paz, los turistas visitan el Parque Nacional Montecristo y disfrutan de la rica biodiversidad de la selva nubosa.${ suffix }En la región occidental, los artesanos trabajan en talleres familiares, creando hermosas artesanías de barro y textiles.${ suffix }En Chalatenango, los excursionistas hacen senderismo en las montañas de El Pital y disfrutan de vistas impresionantes desde el punto más alto de El Salvador.${ suffix }En la región costera, los pescadores capturan mariscos frescos como camarones y langostinos, que luego se venden en los mercados locales.${ suffix }En Usulután, los turistas visitan la Reserva Natural El Imposible y exploran la exuberante selva tropical y las impresionantes cascadas.${ suffix }En el departamento de Cabañas, los visitantes disfrutan del ecoturismo y la observación de aves en el Parque Nacional El Trifinio.${ suffix }`,
    code: `es-SV`,
    macro: `es`,
  }
}
