export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a Uruguay, iluminando las calles de Montevideo y las extensas llanuras de la campiña. Los uruguayos se despiertan con el aroma del mate y el sonido de los pájaros en el campo.${ suffix }María, una residente de Punta del Este, se levanta temprano para ir a la playa a caminar mientras el sol comienza a brillar sobre el océano Atlántico. La brisa marina le da energía para empezar el día.${ suffix }En la capital, los estudiantes se preparan para un nuevo día de clases en la Universidad de la República, mientras los trabajadores comienzan su jornada laboral en el centro de la ciudad.${ suffix }En la región de Colonia, los agricultores cosechan uvas en los viñedos y producen vinos de alta calidad en las bodegas locales.${ suffix }En Tacuarembó, los gauchos montan a caballo y cuidan del ganado en las vastas estancias de la región, manteniendo vivas las tradiciones criollas.${ suffix }En Rocha, los turistas disfrutan de la naturaleza virgen y las playas desiertas, explorando parques nacionales y reservas naturales.${ suffix }En Salto, los termalistas se relajan en las aguas termales y disfrutan de tratamientos de spa en los complejos turísticos de la región.${ suffix }En Paysandú, los pescadores salen al río Uruguay en busca de dorados y surubíes, mientras los turistas disfrutan de la pesca deportiva.${ suffix }En Artigas, los mineros extraen piedras semipreciosas en las minas de amatista y cuarzo, contribuyendo a la economía local.${ suffix }En Maldonado, los artesanos venden sus productos en la feria de la Plaza Artigas, mostrando su talento y creatividad.${ suffix }En Durazno, los ciclistas participan en la Vuelta Ciclista del Uruguay, compitiendo en una de las carreras más importantes del país.${ suffix }En Florida, los agricultores cultivan arroz y soja en los campos fértiles del departamento, contribuyendo a la producción agrícola del país.${ suffix }En Treinta y Tres, los turistas visitan el Fuerte de San Miguel, un sitio histórico que conmemora la Batalla de Sarandí.${ suffix }En Lavalleja, los excursionistas hacen senderismo en las sierras y exploran cuevas y cascadas escondidas, disfrutando de la belleza natural.${ suffix }`,
    code: `es-UY`,
    macro: `es`,
  }
}
