export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a los Estados Unidos, iluminando las bulliciosas calles de Nueva York y las tranquilas carreteras de los pueblos rurales de Kansas. Los neoyorquinos se despiertan con el olor del café y el sonido de los taxis pitando en la calle.${ suffix }María, una residente de Los Ángeles, se levanta temprano para ir a correr por la playa mientras el sol comienza a asomarse por el horizonte. El aire fresco del océano le da energía para comenzar el día.${ suffix }En Washington D.C., los políticos se preparan para un nuevo día en el Capitolio, discutiendo leyes y políticas que afectarán al país.${ suffix }En Texas, los granjeros salen al campo para cuidar de sus cultivos de maíz y ganado, mientras el sol del desierto calienta la tierra.${ suffix }En San Francisco, los programadores de tecnología comienzan a trabajar en las nuevas innovaciones que cambiarán el mundo, mientras disfrutan de una taza de café en un café local.${ suffix }En Florida, los turistas disfrutan del sol y la diversión en los parques temáticos de Orlando y las playas de Miami.${ suffix }En Chicago, los trabajadores de la construcción comienzan a trabajar en los rascacielos de la ciudad, mientras los transeúntes caminan por las bulliciosas calles del centro.${ suffix }En Alaska, los pescadores salen al mar en busca de salmón fresco, mientras las auroras boreales iluminan el cielo nocturno.${ suffix }En Hawái, los surfistas disfrutan de las olas en las hermosas playas de arena blanca, mientras los lugareños preparan un tradicional luau para la noche.${ suffix }En Dakota del Norte, los agricultores cosechan trigo en los vastos campos que se extienden hasta donde alcanza la vista.${ suffix }En Las Vegas, los turistas juegan en los casinos y disfrutan de los espectáculos de entretenimiento mientras la ciudad brilla con luces de neón.${ suffix }En Maine, los pescadores salen al mar en sus barcos pesqueros, en busca de langosta fresca y otros mariscos.${ suffix }En Colorado, los excursionistas suben a las montañas para disfrutar de la belleza natural y las actividades al aire libre que ofrece el estado.${ suffix }En Luisiana, los músicos tocan jazz en los bares de Nueva Orleans, mientras los turistas disfrutan de la comida cajún y las festividades en la calle Bourbon.${ suffix }En Oregón, los amantes del aire libre exploran los parques nacionales y las reservas naturales, maravillándose con la diversidad de paisajes.${ suffix }`,
    code: `es-US`,
    macro: `es`,
  }
}
