export function getText(options = {}) {
  const {
    suffix,
  } = options

  return {
    text: `La mañana llega a Venezuela, iluminando las coloridas calles de Caracas y las playas doradas de Margarita. Los caraqueños se despiertan con el aroma del café y el sonido de la ciudad despertando.${ suffix }María, una residente de Maracaibo, se levanta temprano para preparar el desayuno mientras escucha el canto de los pájaros en su patio. El sol brilla sobre el lago de Maracaibo.${ suffix }En los Llanos, los vaqueros se preparan para un día de trabajo en las extensas llanuras, cuidando del ganado y disfrutando del aire libre.${ suffix }En Mérida, los turistas se preparan para explorar los Andes venezolanos, maravillándose con los paisajes montañosos y las oportunidades de aventura.${ suffix }En la Isla de Margarita, los vendedores ambulantes ofrecen cocos frescos y artesanías en las playas, mientras los turistas disfrutan del sol y el mar.${ suffix }En Puerto La Cruz, los pescadores salen al mar en sus botes pesqueros, buscando la captura del día para abastecer los mercados locales.${ suffix }En la Gran Sabana, los viajeros admiran los tepuyes y las cascadas, maravillándose con la belleza natural de esta región única.${ suffix }En Ciudad Guayana, los trabajadores se preparan para un día en las fábricas y las industrias, contribuyendo al desarrollo económico del país.${ suffix }En los Andes venezolanos, los campesinos cosechan café y cacao en las laderas de las montañas, produciendo algunos de los mejores productos agrícolas del país.${ suffix }En Carabobo, los turistas visitan los viñedos y bodegas, degustando los vinos locales y aprendiendo sobre la historia vinícola de la región.${ suffix }En Los Roques, los turistas disfrutan del buceo y el snorkel en las aguas cristalinas, explorando los arrecifes de coral y la vida marina.${ suffix }En Barquisimeto, los músicos y bailarines se reúnen para celebrar la Feria Internacional de la Divina Pastora, con música, bailes y desfiles.${ suffix }En el Delta del Orinoco, los ecoturistas exploran los manglares y los canales de agua, observando aves exóticas y otras especies de la fauna.${ suffix }En Táchira, los agricultores cultivan plátanos y café en las tierras fértiles de la región, contribuyendo a la agricultura del país.${ suffix }En la Península de Paraguaná, los turistas visitan las dunas de arena y las playas vírgenes, disfrutando del sol y el viento del mar.${ suffix }`,
    code: `es-VE`,
    macro: `es`,
  }
}
