name: Release & Publish to Npm

on: workflow_dispatch

jobs:
  quality-check:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/prepare
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Release
        run: pnpm run release:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
